name = "ExamplePkg"
uuid = "636a3205-dd30-4e5c-9b2a-d56f40c4ed2d"
authors = ["ikr5146 <zekeross1517@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
